api:
  jwt:
    secret: testSecretKey

logging:
    level:
        root: WARN

spring:
    main:
        banner-mode: off
    web:
        error:
            include-stacktrace: never
    
springdoc:
    api-docs:
        enabled: false

scalar:
  enabled: false